# Generated by Django 4.2 on 2023-04-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_area_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='parent_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='forum.area'),
        ),
    ]
