# Generated by Django 4.2 on 2023-04-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_area_parent_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='parent_area',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
    ]
