# Generated by Django 4.2 on 2023-04-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_postagem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='title',
        ),
    ]
