# Generated by Django 4.2 on 2023-04-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_area_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='nome',
        ),
    ]
