# Generated by Django 4.2 on 2023-04-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
