# Generated by Django 4.2 on 2023-04-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Postagem',
        ),
    ]
